export const addIngredient = 'ADD_INGREDIENT'
export const removeIngredient = 'REMOVE_INGREDIENT'
export const setIngredients = 'SET_INGREDIENTS'
export const fetchIngredientsFailed = 'FETCH_INGREDIENTS_FAILED'
export const purchaseBurgerSuccess = 'PURCHASE_BURGER_SUCCESS'
export const purchaseBurgerFail = 'PURCHASE_BURGER_FAIL'
export const purchaseBurgerStart = 'PURCHASE_BURGER_START'
export const purchaseInit = 'PURCHASE_INIT'

export const fetchOrderStart = 'FETCH_ORDER_START'
export const fetchOrderSuccess = 'FETCH_ORDER_SUCCESS'
export const fetchOrderFail = 'FETCH_ORDER_FAIL'  

export const authStart = 'AUTH_START'
export const authSuccess = 'AUTH_SUCCESS'
export const authFail = 'AUTH_FAIL'
export const logout = 'LOGOUT'
export const setAuth = 'SET_AUTH'
